version: '2'

services:
  app:
    image: tutum/hello-world:latest
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: production
      SERVICE_80_NAME: http
      SERVICE_80_CHECK_HTTP: .
      SERVICE_80_CHECK_INTERVAL: 15s
    ports:
    - "80"

  lb:
    build: ./
    links:
    - consul
    ports:
    - "80:80"
    environment:
    - SERVICE_80_CHECK_HTTP=.

  consul:
    command: -server -bootstrap #-advertise 0.0.0.0
    image: gliderlabs/consul-server:latest
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

  registrator:
    command: -internal=true consul://consul:8500
    image: gliderlabs/registrator:latest
    links:
    - consul
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

